name: Daily Fallen Heroes Memorial
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at noon UTC
  workflow_dispatch:

jobs:
  post-memorial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install requests beautifulsoup4
    - name: Post Memorial
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      run: python query-fallen.py