name: Daily Fallen Heroes Memorial

on:
  # Run daily at 12:00 PM UTC (8:00 AM EST / 7:00 AM CST)
  schedule:
    - cron: '0 12 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      search_mode:
        description: 'Search mode to use'
        required: false
        default: 'daily'
        type: choice
        options:
          - daily
          - comprehensive
          - recent

jobs:
  post-memorial:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify Facebook credentials
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      run: |
        if [ -z "$FB_ACCESS_TOKEN" ]; then
          echo "❌ FB_ACCESS_TOKEN secret not set"
          exit 1
        fi
        if [ -z "$FB_PAGE_ID" ]; then
          echo "❌ FB_PAGE_ID secret not set"
          exit 1
        fi
        echo "✅ Facebook credentials are configured"
        
    - name: Run fallen heroes memorial script
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        SEARCH_MODE: ${{ github.event.inputs.search_mode || 'daily' }}
        USE_PROXY: 'false'
      run: |
        echo "🇺🇸 Starting Fallen Heroes Memorial Script 🇺🇸"
        echo "Search Mode: $SEARCH_MODE"
        echo "Timestamp: $(date)"
        python soldier-fb.py
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs-${{ github.run_number }}
        path: |
          *.log
          error_*.txt
        retention-days: 7
        
    - name: Notify on success
      if: success()
      run: |
        echo "✅ Daily memorial post completed successfully"
        echo "🇺🇸 Honor and remember our fallen heroes 🇺🇸"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Daily memorial post failed"
        echo "Check the logs and error artifacts for details"